app/zogue_site/config/routes.rb
Rails.application.routes.draw do
  
  get 'navigate/index'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :clips
 
  get 'user_mailer/alert'
  get 'user_mailer/confirm'

  resources :subcategories
  get 'errors/error404'

  resources :sites
  resources :statistics
  resources :human_interactions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :branches do
    member do
      put "like" => "branches#upvote"
      put "unlike" => "branches#downvote"
    end
  end

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
  
  get 'plataform/about'

  get 'categories/showimages/:id' => "categories#showimages"
  
  get 'plataform/team'

  get 'profile/createprofile/:id' => "profile#createprofile", :as => :createprofile_profile

  get 'plataform/jobs'
  get 'plataform/contact'

  get 'plataform/ana'
  get "subcategories/" => "subcategories#index", :as => :subcategories_index
  get 'news/pictures'
  get 'news/pictures' => 'news#pictures', :as => :news_picture
  get "/branches/:id/edit" => "branches#edit", :as => :branches_edit
  get "/branches/destroy/:id" => "branches#destroy", :as => :branches_destroy

  get "/navigate/:id" => "navigate#index"
  get "/save/:new_id/destroy/:clip_id" => "save#destroy", :as => :save_destroy

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  resources :categories
  resources :news
  resources :news do
    member do
      put "create" => "news#create"
      put "like" => "news#upvote"
      put "unlike" => "news#downvote"

    end
  end

  put "uploadPictures" => "news#uploadPictures"
  put "create" => "profile#create"
  post "profile/create"
  post "save/create"
  post "news/create", :as => :create_news
  post "pictures/create", :as => :create_pictures

  get 'home/index'
  get "profile/:id" => "profile#index"
  get "/clips" => "clips#index", :as => :clips_index
  

  devise_for :users, controllers: {
    registrations: "my_devise/registrations"
  }

  root 'news#index'

  get '/human_interactions/create' => 'human_interactions#create', :as => :create_interaction
  resources :human_interactions
  

  get "/users" => "users#sign_in"
  get "/home" => "home#index"
  get "/plataform" => "plataform#about"
  get "/zadpanel13" => "zadpanel13#index"

end

app/zogue_site/app/views/layouts/_footer.html.erb
<div class="row">
				<div class="col-md-4"></div>
					<ul class="col-md-2 footerNav">
						<li>
							<a style="color:white;" href="/plataform/about">	About
							</a>
						</li>
						<li>
							<a style="color:white;" class="footerA" href="/plataform/team">
								Team
							</a>
						</li>
						<li>
							<a style="color:white;" class="footerA" href="/plataform/jobs">
								Jobs
							</a>
						</li>
						<li>
							<a style="color:white;" class="footerA" href="/plataform/contact">
								Contact
							</a>
						</li>
					</ul>
				<div class="col-md-2">
				    
				</div>
				<div class="col-md-4"></div>
				</div>
				<div class="row">
				<span class="footerLabel">©Zogue- All rights reserved</span>
			</div>

app/zogue_site/app/views/layouts/_loggedSet.html.erb
<!--http://stackoverflow.com/questions/2165665/how-do-i-get-the-current-absolute-url-in-ruby-on-rails -->
<%= image_tag(current_user.avatar.url(:thumb), :class => "img-circle", :style=> "height:70px;") %>

<% if request.fullpath != news_index_path %>
   <button onclick="window.location.href='/news'" class="btn btn-primary">
	    <strong>Go to Newspaper</strong>
   </button>
<%else%>
	
   <button onclick="window.location.href='/news'" class="btn btn-primary disabled">
	    <strong>Go to Newspaper</strong>
   </button>

<% end %>


<button type="button" class="btn  btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	<strong>Account</strong> <span class="caret"></span>
</button>  


<ul class="dropdown-menu dropdown-menu-right">
	<li class="list-group-item" style="text-align:center;">
		<strong>
			<a href="/profile/<%= @user_id %>">
				<%=@user_name%>
			</a>
		</strong>
	</li>
			
	<li class="list-group-item" style="text-align:center;">
		<%= link_to("Clipping", clips_index_path)%>
	
	</li>
		
	<li class="list-group-item" style="text-align:center;">
		<%= link_to("Home", home_path)%>
	</li>

		
	<li class="list-group-item list-group-item-danger" style="text-align:center;">	
		 <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>  
	</li>  
</ul>        

app/zogue_site/app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-warning">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li style="text-align:center;">
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/zogue_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Zogue</title>
 
  <%= favicon_link_tag 'fav.png' %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "jquery.bxslider" %>


  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults, "rails.validations", "rails.validations.custom"%>
  <%= javascript_include_tag "jquery.bxslider"%>
  

  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"%>
  <%= javascript_include_tag "jquery.tokeninput"%>
  <%= stylesheet_link_tag "token-input" %>

  <%= javascript_include_tag "bootstrap-tagsinput"%>
  <%= stylesheet_link_tag "bootstrap-tagsinput" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">
	  //Avoid horizontal scrolling
	  var scrollEventHandler = function()
	  {
	  	window.scroll(0, window.pageYOffset)
	  }
	  window.addEventListener("scroll", scrollEventHandler, false);
  </script>
  <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body>
	 <header class="row">
		<div class="col-md-1"></div>
		<div class="col-md-3" id="logo">
		
		<a href="/news">
		<%= image_tag "logo.png", :alt => "logo", :title => "logo" %>
		</a>

		</div>
		
		<div class="col-md-4">
		</div>
		

		<div class="col-md-4">
			 <div style="margin-top:5px;">
			 	<%= yield :button_set %>      
			 </div>
		</div>		
	</header>

	<main class="row">
		<%= render 'layouts/messages' %>
		<%= yield %>
	</main>

	<footer class="row">
		<%= yield :footer %>
	</footer>
	
</body>
</html>