app/zogue_site/config/routes.rb
Rails.application.routes.draw do
  
  get 'navigate/index'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :clips
 
  get 'user_mailer/alert'
  get 'user_mailer/confirm'

  resources :subcategories
  get 'errors/error404'

  resources :sites
  resources :statistics
  resources :human_interactions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :branches do
    member do
      put "like" => "branches#upvote"
      put "unlike" => "branches#downvote"
    end
  end

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
  
  get 'plataform/about'

  get 'categories/showimages/:id' => "categories#showimages"
  
  get 'plataform/team'

  get 'profile/createprofile/:id' => "profile#createprofile", :as => :createprofile_profile

  get 'plataform/jobs'
  get 'plataform/contact'

  get 'plataform/ana'
  get "subcategories/" => "subcategories#index", :as => :subcategories_index
  get 'news/pictures'
  get 'news/pictures' => 'news#pictures', :as => :news_picture
  get "/branches/:id/edit" => "branches#edit", :as => :branches_edit
  get "/branches/destroy/:id" => "branches#destroy", :as => :branches_destroy

  get "/navigate/:id" => "navigate#index"
  get "/save/:new_id/destroy/:clip_id" => "save#destroy", :as => :save_destroy

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  resources :categories
  resources :news
  resources :news do
    member do
      put "create" => "news#create"
      put "like" => "news#upvote"
      put "unlike" => "news#downvote"

    end
  end

  put "uploadPictures" => "news#uploadPictures"
  put "create" => "profile#create"
  post "profile/create"
  post "save/create"
  post "news/create", :as => :create_news
  post "pictures/create", :as => :create_pictures

  get 'home/index'
  get "profile/:id" => "profile#index"
  get "/clips" => "clips#index", :as => :clips_index
  

  devise_for :users, controllers: {
    registrations: "my_devise/registrations"
  }

  root 'news#index'

  get '/human_interactions/create' => 'human_interactions#create', :as => :create_interaction
  resources :human_interactions
  

  get "/users" => "users#sign_in"
  get "/home" => "home#index"
  get "/plataform" => "plataform#about"
  get "/zadpanel13" => "zadpanel13#index"

end

app/zogue_site/app/models/clip.rb
class Clip < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :news,:class_name => "News"
end

app/zogue_site/app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  before_action :set_clip, only: [:show, :edit, :update, :destroy]

  # GET /clips
  # GET /clips.json
  def index
    user = User.find(current_user.id)
    @clips = user.clips
    @clip = Clip.new
    @news = News.all
  end

  # GET /clips/new
  def new
    @clip = Clip.new
  end

  # GET /clips/1/edit
  def edit
  end

  # POST /clips
  # POST /clips.json
  def create
    @clip = Clip.new(clip_params)

    respond_to do |format|
      if @clip.save
        format.html { redirect_to clips_index_path, notice: 'Clip was successfully created.' }
        format.json { render :show, status: :created, location: @clip }
      else
        format.html { render :new }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /clips/1
  # PATCH/PUT /clips/1.json
  def update
    respond_to do |format|
      if @clip.update(clip_params)
        format.html { redirect_to @clip, notice: 'Clip was successfully updated.' }
        format.json { render :show, status: :ok, location: @clip }
      else
        format.html { render :edit }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clips/1
  # DELETE /clips/1.json
  def destroy
    @clip.destroy
    respond_to do |format|
      format.html { redirect_to clips_url, notice: 'Clip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clip
      @clip = Clip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clip_params
      params.require(:clip).permit(:name, :description, :user_id)
    end
end

app/zogue_site/app/helpers/clips_helper.rb
module ClipsHelper
end

app/zogue_site/app/views/clips/_form.html.erb
<%= simple_form_for(@clip) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="form-actions" style="text-align:center;">
    <%= f.button :submit, :class=> "btn btn-primary" %>
  </div>
<% end %>

app/zogue_site/app/views/clips/edit.html.erb
<h1>Editing Clip</h1>

<%= render 'form' %>

<%= link_to 'Show', @clip %> |
<%= link_to 'Back', clips_path %>

app/zogue_site/app/views/clips/index.html.erb
<% content_for :button_set do %>
       <%= render 'layouts/loggedSet' %>
<%end%>



<div class="col-md-1">
</div>
<div class="col-md-10">
  
  <div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#new-clip" aria-controls="home" role="tab" data-toggle="tab">    
        <span>
             <%= image_tag "glyphicons_free/glyphicons/png/glyphicons-433-plus.png", :alt => "plus", :title => "plus" %>
          </span>

       New Clip
      </a>
    </li>

    <% @clips.each do |clip|%>
      <li role="presentation">
        <a href="#tab-<%= clip.id %>" aria-controls="profile" role="tab" data-toggle="tab">
          <span>
             <%= image_tag "glyphicons_free/glyphicons/png/glyphicons-63-paperclip.png", :alt => "clip", :title => "clip" %>
          </span>
          <%= clip.name%>
        </a>
      </li>
    <%end%>

  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="new-clip">
      <div class="col-md-3"></div>
      <div class="col-md-6 well">

        <h1>New Clip</h1>
        <%= render 'form' %>

      </div>
      <div class="col-md-3"></div>

    </div>
     
    <% @clips.each do |clip| %>
       <div role="tabpanel" class="tab-pane" id="tab-<%= clip.id %>">   
          <div class="alert alert-info row">
          <div  style="text-align:center;">
          <%= link_to 'Edit', edit_clip_path(clip), :class=>"btn btn-success", :style=>"color:white; font-weight:bold;" %>
          <%= link_to 'Destroy', clip, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", :style=>"color:white; font-weight:bold;" %>
          </div>
          <p>
            <strong>Name:</strong><%= clip.name %>
          </p>
          <p>
            <strong>Description:</strong><%= clip.description %>
          </p>

          </div>

            <% if !clip.news.blank?%>
              <div>

                <% for x in clip.news%>
                 <div class="row well">
                 <div class="col-md-3">
                  <p class="newImage">
                    <%= image_tag x.image(:medium), :class => "img-thumbnail" %>
                  </p>
                 </div>

                 <div class="col-md-9">
                  <h4>
                    <a href="<%=x.Url%>">
                      <%= x.Title %>
                    </a>
                  </h4>
                  <p>
                    <em>
                     <strong>Created at</strong> <%= time_ago_in_words(x.created_at)%> ago
                    </em>
                  </p>
                  
                  <p>
                    <strong>Source Site:</strong>
                  </p>

                  <div>
                      <%=link_to "Destroy", save_destroy_path(x.id, clip.id), :class=> "btn btn-danger", :style => "color:white; font-weight:bold;", data: { confirm: 'Are you sure?' } %>
                  </div>

                 </div>

                 </div> 
                <% end %>

              </div>
            <% else %>
              <div style="text-align:center;">
                <h1>No news here</h1>

              </div>
            <% end %>
       </div>
    <% end %>

  </div>

  </div>
</div>
<div class="col-md-1"></div>

app/zogue_site/app/views/clips/new.html.erb
<h1>New Clip</h1>

<%= render 'form' %>

<%= link_to 'Back', clips_path %>