app/zogue_site/config/routes.rb
Rails.application.routes.draw do
  
  get 'navigate/index'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :clips
 
  get 'user_mailer/alert'
  get 'user_mailer/confirm'

  resources :subcategories
  get 'errors/error404'

  resources :sites
  resources :statistics
  resources :human_interactions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :branches do
    member do
      put "like" => "branches#upvote"
      put "unlike" => "branches#downvote"
    end
  end

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
  
  get 'plataform/about'

  get 'categories/showimages/:id' => "categories#showimages"
  
  get 'plataform/team'

  get 'profile/createprofile/:id' => "profile#createprofile", :as => :createprofile_profile

  get 'plataform/jobs'
  get 'plataform/contact'

  get 'plataform/ana'
  get "subcategories/" => "subcategories#index", :as => :subcategories_index
  get 'news/pictures'
  get 'news/pictures' => 'news#pictures', :as => :news_picture
  get "/branches/:id/edit" => "branches#edit", :as => :branches_edit
  get "/branches/destroy/:id" => "branches#destroy", :as => :branches_destroy

  get "/navigate/:id" => "navigate#index"
  get "/save/:new_id/destroy/:clip_id" => "save#destroy", :as => :save_destroy

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  resources :categories
  resources :news
  resources :news do
    member do
      put "create" => "news#create"
      put "like" => "news#upvote"
      put "unlike" => "news#downvote"

    end
  end

  put "uploadPictures" => "news#uploadPictures"
  put "create" => "profile#create"
  post "profile/create"
  post "save/create"
  post "news/create", :as => :create_news
  post "pictures/create", :as => :create_pictures

  get 'home/index'
  get "profile/:id" => "profile#index"
  get "/clips" => "clips#index", :as => :clips_index
  

  devise_for :users, controllers: {
    registrations: "my_devise/registrations"
  }

  root 'news#index'

  get '/human_interactions/create' => 'human_interactions#create', :as => :create_interaction
  resources :human_interactions
  

  get "/users" => "users#sign_in"
  get "/home" => "home#index"
  get "/plataform" => "plataform#about"
  get "/zadpanel13" => "zadpanel13#index"

end

app/zogue_site/app/models/site.rb
class Site < ActiveRecord::Base
end

app/zogue_site/app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :authorize
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:Name, :Url, :Country, :State, :Model, :category_id, :last_scrapped, :score)
    end

    def authorize
      redirect_to(root_path) unless user_signed_in? and current_user.is_admin?
    end
end

app/zogue_site/app/helpers/sites_helper.rb
module SitesHelper
end

app/zogue_site/app/views/sites/_form.html.erb
<%= simple_form_for(@site) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :Name %>
    <%= f.input :Url %>
    <%= f.input :Country %>
    <%= f.input :State %>
    <%= f.input :Model %>
    <%= f.input :category_id %>
    <%= f.input :last_scrapped %>
    <%= f.input :score %>
  </div>

  <div class="form-actions" style="text-align:center;">
    <%= f.button :submit %>
  </div>
<% end %>

app/zogue_site/app/views/sites/edit.html.erb
<div class="col-md-2"></div>
<div class="col-md-8">
<h1>Editing Site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>
</div>
<div class="col-md-2"></div>

app/zogue_site/app/views/sites/index.html.erb
<script type="text/javascript">
  $(function(){

    $(".modelTD").each(function(){

      if($(this).text() == "train"){
        $(this).parent().addClass("info");
      }

      else{
        $(this).parent().addClass("active");
      }

    });


  });

</script>

<div class="col-md-1"></div>
<div class="col-md-10 well">
<p id="notice"><%= notice %></p>
<h1>Listing Sites</h1>

<p>
  <%= link_to 'New Site', new_site_path, :class => "btn btn-primary", :style =>"color:white;" %>
</p>
<hr/>
<p>
 &nbsp;The sites listed here will be used by our classification algorithm, so be
 careful!
</p>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Country</th>
      <th>State</th>
      <th>Model</th>
      <th>Category</th>
      <th>Last scrapped</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.Name %></td>
        <td><%= site.Url %></td>
        <td><%= site.Country %></td>
        <td><%= site.State %></td>
        <td class="modelTD"><%= site.Model %></td>
        <td><%= site.category_id %></td>
        <td><%= site.last_scrapped %></td>
        <td><%= site.score %></td>
        <td><%= link_to 'Edit', edit_site_path(site), :style=> "color:white;", :class => "btn btn-success" %></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", :style => "color:white;" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="col-md-1"></div>

app/zogue_site/app/views/sites/new.html.erb
<div class="col-md-2"></div>
<div class="col-md-8 well">
<h1>New Site</h1>

<%= render 'form' %>


<%= link_to 'Back', sites_path %>
</div>

<div class="col-md-2"></div>

app/zogue_site/app/views/sites/show.html.erb
<div class="col-md-2"></div>
<div class="col-md-8 well">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @site.Name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @site.Url %>
</p>

<p>
  <strong>Country:</strong>
  <%= @site.Country %>
</p>

<p>
  <strong>State:</strong>
  <%= @site.State %>
</p>

<p>
  <strong>Model:</strong>
  <%= @site.Model %>
</p>

<p>
  <strong>Category:</strong>
  <%= @site.category_id %>
</p>

<p>
  <strong>Last scrapped:</strong>
  <%= @site.last_scrapped %>
</p>

<p>
  <strong>Score:</strong>
  <%= @site.score %>
</p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>
</div>
<div class="col-md-2"></div>