app/zogue_site/config/routes.rb
Rails.application.routes.draw do
  
  get 'navigate/index'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :clips
 
  get 'user_mailer/alert'
  get 'user_mailer/confirm'

  resources :subcategories
  get 'errors/error404'

  resources :sites
  resources :statistics
  resources :human_interactions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :branches do
    member do
      put "like" => "branches#upvote"
      put "unlike" => "branches#downvote"
    end
  end

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
  
  get 'plataform/about'

  get 'categories/showimages/:id' => "categories#showimages"
  
  get 'plataform/team'

  get 'profile/createprofile/:id' => "profile#createprofile", :as => :createprofile_profile

  get 'plataform/jobs'
  get 'plataform/contact'

  get 'plataform/ana'
  get "subcategories/" => "subcategories#index", :as => :subcategories_index
  get 'news/pictures'
  get 'news/pictures' => 'news#pictures', :as => :news_picture
  get "/branches/:id/edit" => "branches#edit", :as => :branches_edit
  get "/branches/destroy/:id" => "branches#destroy", :as => :branches_destroy

  get "/navigate/:id" => "navigate#index"
  get "/save/:new_id/destroy/:clip_id" => "save#destroy", :as => :save_destroy

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  resources :categories
  resources :news
  resources :news do
    member do
      put "create" => "news#create"
      put "like" => "news#upvote"
      put "unlike" => "news#downvote"

    end
  end

  put "uploadPictures" => "news#uploadPictures"
  put "create" => "profile#create"
  post "profile/create"
  post "save/create"
  post "news/create", :as => :create_news
  post "pictures/create", :as => :create_pictures

  get 'home/index'
  get "profile/:id" => "profile#index"
  get "/clips" => "clips#index", :as => :clips_index
  

  devise_for :users, controllers: {
    registrations: "my_devise/registrations"
  }

  root 'news#index'

  get '/human_interactions/create' => 'human_interactions#create', :as => :create_interaction
  resources :human_interactions
  

  get "/users" => "users#sign_in"
  get "/home" => "home#index"
  get "/plataform" => "plataform#about"
  get "/zadpanel13" => "zadpanel13#index"

end

app/zogue_site/app/models/category.rb
class Category < ActiveRecord::Base
 has_many :news,:class_name => "News"
 has_many :pictures, :dependent => :destroy
 has_many :subcategories
 validates :Name, presence: true
 validates :Description, presence: true
 
 has_and_belongs_to_many :users

 accepts_nested_attributes_for :pictures, :reject_if => lambda { |t| t['picture'].nil? }
end

app/zogue_site/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authorize, only: [:index, :new, :edit, :create, :update, :destroy]
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
   
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    if signed_in?
      @branches = Branch.all
      @user_name = current_user.name
      @user_id = current_user.id
      @branch = Branch.new
    end

    @human_interaction = HumanInteraction.new
    
    #@filtered_categories[0].news

    @news = News.all.order(:cached_votes_up => :desc)
    @last_update = Time.now.strftime('%H:%M')
    @categories_name = Category.pluck(:Name)

    authorize! :read, @news

    @category_id =  params[:id]
    @category = Category.find(@category_id)
    @category_name = Category.where(id: @category_id).pluck(:Name)[0]
    @uncategorized = @category.news.where(subcategory_id: 0)

    #@pics_id = category.pictures.pluck(:id) #pics_id of a specific category 
    #@images = Dir.glob("#{Rails.root}/public/system/pictures/images/000/000/#{@category_id}/*.jpg" )
  end

  def showimages
    @category_images = Picture.where(category_id: params[:id])
    @category = Category.find(params[:id])
    @picture = Picture.new
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        if params[:images]
          params[:images].each { |image|
            @category.pictures.create(image: image)
          }
        end

        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
         if params[:images]
          params[:images].each { |image|
            @category.pictures.create(image: image)
          }
        end

        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:Name, :Description)
    end

    def authorize
      redirect_to(root_path) unless user_signed_in? and current_user.is_admin?
    end

end

app/zogue_site/app/helpers/categories_helper.rb
module CategoriesHelper
	def filtertodayNews(all_news)
		return all_news.where(news_edition: DateTime.now.to_date )
	end
end

app/zogue_site/app/views/categories/_form.html.erb
<%= form_for(@category, :html => {:multipart => true} ) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name, :placeholder => "Name", :class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description, :placeholder=>"Description", :class=>"form-control" %>
  </div>

  <div class="control-group">
    <%= f.label :pictures, :class => 'control-label' %>
    <div class="controls">
      <p>
        <%= f.label :image, "Image File", multiple: true %>
        <%= file_field_tag "images[]", type: :file, multiple: true %>
      </p>
    </div>


  </div>

  <div class="actions" style="text-align:center;">
    <%= f.submit  'Save', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/zogue_site/app/views/categories/edit.html.erb
<div class="col-md-4"></div>
<div class="col-md-4 well centralizeVertical">
	<h1>Editing Category</h1>
	<%= render 'form' %>
	<%= link_to 'Show', @category %> |
	<%= link_to 'Back', categories_path %>
</div>
<div class="col-md-4"></div>

app/zogue_site/app/views/categories/index.html.erb
<% content_for :button_set do %>
    <% if user_signed_in? %>
       <%= render 'layouts/loggedSet' %>
    <% else %>
      <button style="margin-top:0px;" onclick="window.location.href='/users/sign_in'" class="col-md-3 btn btn-primary btn-lg" id="enterBtn">
        Enter
      </button>
    <% end %>                 
<%end%>

<div class="col-md-3"></div>
<div class="col-md-6 well centralizeVertical">
  <p id="notice"><%= notice %></p>
  <h1>Listing Categories</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          
          <td><%= category.Name %></td>
          <td><%= category.Description %></td>
          <td><%= link_to 'Show', category %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <p style="text-align:center;">
  <%= link_to 'New Category', new_category_path, :style=> "color:white; font-weight:bold;",:class=> "btn btn-primary" %>
  </p>
</div>
<div class="col-md-3"></div>

app/zogue_site/app/views/categories/new.html.erb
<div class="col-md-3"></div>

<div class="col-md-6 well centralizeVertical">
	<h1>New Category</h1>

	<%= render 'form' %>

	<%= link_to 'Back', categories_path %>
</div>

<div class="col-md-3"></div>

app/zogue_site/app/views/categories/show.html.erb
<% content_for :button_set do %>
    <% if user_signed_in? %>
       <%= render 'layouts/loggedSet' %>
    <% else %>
      <button style="margin-top:0px;" onclick="window.location.href='/users/sign_in'" class="col-md-3 btn for new in btn-primary btenterBtn">
        Enter
        </button>
    <% end %>                 
<%end%>

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-11">
    <h1 id="categoryLabel">
        <%= @category.Name.capitalize %>
    </h1>
    <hr/>
  </div>
</div>

<% if !@category.news.blank?%> 
  <% if !@category.subcategories.blank? %>
     <% for s in @category.subcategories %>          
        <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-10">
            <h2>&#10146;<%= s.Name %></h2>  
            <% for x in filtertodayNews(s.news) %>
              <%= render :partial => "news/new", locals: {:x => x} %>
            <% end %>      
          </div>
          <div class="col-md-1"></div>
        </div>
    <% end %>

     <% for u in @uncategorized %>          
        <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-10">
            <h2>&#10146;Sem categoria</h2>  
            <% for x in filtertodayNews(u) %>
              <%= render :partial => "news/new", locals: {:x => x} %>
            <% end %>      
          </div>
          <div class="col-md-1"></div>
        </div>
    <% end %>

  <% else %>
    <div class="row">
      <div class="col-md-1"></div>  
      <div class="col-md-10">
        <% for x in filtertodayNews2(@category.news) %>
          <%= render :partial => "news/new", locals: {:x => x} %>
        <% end %>
      </div>
      <div class="col-md-1"></div>
    </div>
  <% end %>

<% else %>
  <div class="row">  
    <div class="col-md-1"></div>
    <div class="col-md-11">  
      <h2 style="text-align:center; color:red;">
        Sorry, there aren't news for this category :(
      </h2>
    </div>
  </div>
<% end %>

app/zogue_site/app/views/categories/showimages.html.erb
<div class="col-md-1"></div>
<div class="col-md-10">
<div>
  <!-- Nav tabs -->
   <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#welcome" aria-controls="home" role="tab" data-toggle="tab">Home</a>
    </li>
 
    <% for c in @category.subcategories%>		
		<li role="presentation">
     		<a href="#<%= c.id %>" aria-controls="profile" role="tab" data-toggle="tab">
     			<%=c.Name%>
     		</a>
    	</li>
	<%end%>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active well" id="welcome">
    	Hello
    </div>
    <% for c in @category.subcategories%>		
    <div role="tabpanel" class="tab-pane well" id="<%= c.id %>">
    	<div class="row" style="text-align:center; margin-bottom:10px;">	
			<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#adddialog-<%= c.id %>">
				Add image
			</button>
		</div>

    	<table class="table table-striped well">
			<thead>
				<th>Picture</th>
				<th>Name</th>
				<th>Actions</th>
			</thead>
			<tbody>
				<% for p in c.pictures%>
					<tr>
						<td>
						<%= image_tag p.image(:medium), :class => "img-thumbnail" %>
						</td>
						<td><%=p.image_file_name%></td>
						<td>
							<button class="btn btn-success">
								<strong>Edit</strong>
							</button>
							<button class="btn btn-danger">
								<strong>Destroy</strong>
							</button>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>

		<!-- Trigger the modal with a button -->
		<!-- Modal -->
		<div id="adddialog-<%= c.id %>" class="modal" role="dialog">
		  <div class="modal-dialog">

		    <!-- Modal content-->
		    <div class="modal-content">
		      <div class="modal-header">
		        <h4 class="modal-title">Add images</h4>
		      </div>
		      <div class="modal-body">
		        <strong>Subcategoria:</strong><%= c.Name %>

				<%= form_for(create_pictures_path, :html => {:multipart => true} ) do |f| %>
				  <div class="control-group">
				    <div class="controls">
				      <p>
				        <%= f.label :image, "Image File", multiple: true %>
				        <%= file_field_tag "images[]", type: :file, multiple: true %>
				      </p>
				    </div>
				  </div>

				  <div class="actions" style="text-align:center;">
				    <%= f.submit  'Create', :class => 'btn btn-primary' %>
				  </div>
				<% end %>

		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Close
		        </button>
		      </div>
		    </div>

		  </div>
		</div>


    </div>
  	<%end%>
  </div>
</div>

</div>
<div class="col-md-1"></div>